services:
  frontend:
    container_name: crewless-frontend-development
    build:
      context: ../services/frontend
      dockerfile: dev.dockerfile
    ports:
    - ${FRONTEND_PORT:-3000}:3000 #Browser
    volumes:
    - ../services/frontend:/app
    - /app/node_modules
    environment:
    - NODE_ENV=developpement
  
  backend:
    container_name: crewless-backend-devlopment
    networks:
      - database
    build:
      context: ../services/backend
      dockerfile: dev.dockerfile
    ports:
    - ${BACKEND_PORT:-4000}:4000
    volumes:
      - ../services/backend:/app
      - /app/node_modules
    environment:
    - NODE_ENV=development
    - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public

  postgres:
    image: postgres:18-alpine
    container_name: crewless-database-development
    ports:
      - "5432:5432"
    volumes:
      - ../../database/development:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
    - database
networks:
  database:
    driver: bridge